import { Shield, Lock, Activity, EyeOff, ShieldCheck } from 'lucide-react';

export default function DocsIntroduction() {
  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 ease-out">
      <h1 className="text-4xl font-semibold text-[#0F172A] mb-4">Introduction to SafeLine</h1>
      <p className="text-lg text-[#64748B] mb-8">
        An enterprise-grade deterministic guardrail for AI agents executing in sensitive environments.
      </p>

      <div className="prose prose-slate max-w-none">
        <h2 className="text-2xl font-semibold text-[#0F172A] mt-12 mb-4">What is SafeLine?</h2>
        <p>
          SafeLine acts as an <strong>impenetrable middleware layer</strong> between autonomous AI agents and your production infrastructure. It enforces strict compliance policies, scrubs PII, blocks unauthorized API calls, and maintains a cryptographic audit log of every decision.
        </p>
        <p>
          Unlike probabilistic safety filters that rely on LLMs to judge themselves, SafeLine evaluates agent actions against <strong>deterministic, hard-coded rulesets</strong> before those actions can interact with the outside world.
        </p>

        <div className="grid md:grid-cols-2 gap-6 my-10">
          <div className="bg-[#F8FAFC] border border-[#E2E8F0] p-6 rounded-2xl">
            <ShieldCheck className="w-8 h-8 text-blue-600 mb-4" />
            <h3 className="font-semibold text-[#0F172A] text-lg mb-2 m-0">Zero Trust Verification</h3>
            <p className="text-[#64748B] text-sm m-0">Every API call or command generated by the AI agent is considered hostile until proven compliant.</p>
          </div>
          <div className="bg-[#F8FAFC] border border-[#E2E8F0] p-6 rounded-2xl">
            <Lock className="w-8 h-8 text-blue-600 mb-4" />
            <h3 className="font-semibold text-[#0F172A] text-lg mb-2 m-0">Deterministic Evaluation</h3>
            <p className="text-[#64748B] text-sm m-0">No LLM-in-the-loop for safety validation. Policies are evaluated using strict schema matching and Rego rules.</p>
          </div>
        </div>

        <h2 className="text-2xl font-semibold text-[#0F172A] mt-12 mb-4">Core Principles</h2>
        <ul className="space-y-4 my-6 list-none pl-0">
          <li className="flex items-start gap-3">
            <div className="mt-1 bg-blue-100 p-1 rounded">
              <Activity className="w-4 h-4 text-blue-600" />
            </div>
            <div>
              <strong className="text-[#0F172A] block">Fail Closed</strong>
              <span className="text-[#64748B] text-sm">If an action cannot be definitively proven safe by the current ruleset, it is blocked immediately.</span>
            </div>
          </li>
          <li className="flex items-start gap-3">
            <div className="mt-1 bg-blue-100 p-1 rounded">
              <EyeOff className="w-4 h-4 text-blue-600" />
            </div>
            <div>
              <strong className="text-[#0F172A] block">Privacy by Default</strong>
              <span className="text-[#64748B] text-sm">All outgoing requests are automatically scanned for PII. Detected PII is masked before leaving the perimeter.</span>
            </div>
          </li>
          <li className="flex items-start gap-3">
            <div className="mt-1 bg-blue-100 p-1 rounded">
              <Shield className="w-4 h-4 text-blue-600" />
            </div>
            <div>
              <strong className="text-[#0F172A] block">Immutable Auditing</strong>
              <span className="text-[#64748B] text-sm">Every intercepted request is logged, signed, and hashed to ensure a tamper-proof trail of agent activity.</span>
            </div>
          </li>
        </ul>
      </div>
    </div>
  );
}
